### ISSUE TITLE
awaiting for the decode part

### ISSUE THREAD

**Issue by xikakera** [iamaaditya/neural-paraphrase-generation#1]
it seems the decode part has not been uploaded, wondering when would it be fully uploaded? i wanna compare the result that of the VAE method.

**Comment by iamaaditya** [comment]
@xikakera Decoder is here https://github.com/iamaaditya/neural-paraphrase-generation/blob/master/seq2seq.py#L29 . Also see line #50 on how to use that. I agree it would be much nicer if there was a decode only file where you could pass in the source and get the target out. I am busy this week but next week I will write this file.
