### ISSUE TITLE
datasets question

### ISSUE THREAD

**Issue by joseph12346** [iamaaditya/neural-paraphrase-generation#13]
How to create (neural-paraphrase-generation-dev\data\mscoco)  train_vocab.txt.
THX !

**Comment by iamaaditya** [comment]
Here is an example script to generate the training code. File `captions_train2014.json` and `captions_val2014.json` can be obtained from MSCOCO dataset (see http://cocodataset.org/ )

https://gist.github.com/iamaaditya/bcae0a54b250e62c3be7e78f61de10df
