### ISSUE TITLE
Is this paraphrase generation means learn some paraphrase rule to refine the output of NMT?

### ISSUE THREAD

**Issue by fooSynaptic** [iamaaditya/neural-paraphrase-generation#15]
which still the highest value is applied to sequence generation like NMT and text summary?

**Comment by iamaaditya** [comment]
I have not tried it with NMT datasets. In general, they will improve the readability and diversity of the answers. However, researchers of NMT are too focused on getting the highest BLEU scores for which the exact match is more important. Thus, they do not try paraphrasing models to augment their answers.

**Comment by fooSynaptic** [comment]
I think its really a good try for NMT engineer or researcher. Maybe paraphrase generation can fix the syntex error in the NMT output?
