### ISSUE TITLE
How to calculate the metrics used in this paper?

### ISSUE THREAD

**Issue by egrcc** [iamaaditya/neural-paraphrase-generation#6]
Hi,

It seems that the metrics (BLEU, METEOR, TER) are not calculated in this code. How can I compare the results of this code with those in the paper? Could you please show me the way? Thanks.

**Comment by iamaaditya** [comment]
Original BLEU https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl
Better implementation https://github.com/tensorflow/nmt/blob/master/nmt/utils/evaluation_utils.py
Some more here https://github.com/lium-lst/nmtpy/tree/master/nmtpy/metrics
