### ISSUE TITLE
some error in the MSCOCO dataset

### ISSUE THREAD

**Issue by egrcc** [iamaaditya/neural-paraphrase-generation#7]
### train source:
![_20171107191032](https://user-images.githubusercontent.com/6469953/32490808-7540d60e-c3ef-11e7-8cc5-c78d00c61ab1.png)

### train target:
![_20171107191052](https://user-images.githubusercontent.com/6469953/32490813-77d0dd56-c3ef-11e7-961b-0e4e7b5f2537.png)

**Comment by iamaaditya** [comment]
Sorry I did not check that. I think sentences are still aligned though. This should not cause any issue.
