### ISSUE TITLE
versions for stack used

### ISSUE THREAD

**Issue by tim-hari** [iamaaditya/neural-paraphrase-generation#9]
Hi,

Could you mention the Tensorflow and other packages versions, I'm facing few issues to set up the code.

**Comment by iamaaditya** [comment]
Works for me on TF 1.5 and 1.6.  There are no other dependencies.

**Comment by tim-hari** [comment]
> Works for me on TF 1.5 and 1.6. There are no other dependencies.

Thank you :+1:
